-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('PURCHASE_CONFIRMED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_CANCELED', 'NEW_SUBSCRIBER', 'COURSE_PUBLISHED', 'NEW_REVIEW', 'COMMENT_REPLY', 'ACCESS_EXPIRING', 'SYSTEM') NOT NULL;
